model_name: big_prototype_5
features: [[0, 0, -0.465], 
           [-0.33, -0.2575, 0], 
           [0.33, -0.2575, 0],
           [0.33, 0.2575, 0], 
           [-0.33, 0.2575, 0]]
placement_uncertainty: 0 # default uncertainty will be used if 0 (check feature_model/FeatureModel)
detection_tolerance: 0 # default uncertainty will be used if 0 (check feature_model/FeatureModel)

