model_name: kberg_docking_station
features: [[0, 0, -0.4], # Center.
           [-0.357, -0.3, -0.03], # Top left.
           [0.357, -0.3, -0.03], # Top right.
           [0.357, 0.3, -0.03], # Botttom right.
           [-0.357, 0.3, -0.03]] # Bottom left.
placement_uncertainty: 0 # default uncertainty will be used if 0 (check feature_model/FeatureModel)
detection_tolerance: 0 # default uncertainty will be used if 0 (check feature_model/FeatureModel)
