image_width: 1280
image_height: 720
camera_name: csi_cam_0
camera_matrix:
  rows: 3
  cols: 3
  data: [764.51374,   0.     , 643.29712,
           0.     , 764.69506, 392.25029,
           0.     ,   0.     ,   1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.076666, -0.045728, 0.004071, -0.002003, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [791.00824,   0.     , 639.54312,   0.     ,
           0.     , 789.65247, 395.70318,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
